# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lab6.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lab6.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlab6.proto\x12\x04lab6\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\"\x17\n\x08\x41\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x03\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"%\n\x10JsonImageRequest\x12\x11\n\timage_b64\x18\x01 \x01(\t\"+\n\nImageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\"\n\nDotRequest\x12\t\n\x01\x61\x18\x01 \x03(\x01\x12\t\n\x01\x62\x18\x02 \x03(\x01\"\x17\n\x08\x44otReply\x12\x0b\n\x03\x64ot\x18\x01 \x01(\x01\x32\xc8\x01\n\x04Lab6\x12\'\n\x03\x41\x64\x64\x12\x10.lab6.AddRequest\x1a\x0e.lab6.AddReply\x12\x30\n\x08RawImage\x12\x12.lab6.ImageRequest\x1a\x10.lab6.ImageReply\x12.\n\nDotProduct\x12\x10.lab6.DotRequest\x1a\x0e.lab6.DotReply\x12\x35\n\tJsonImage\x12\x16.lab6.JsonImageRequest\x1a\x10.lab6.ImageReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab6_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=20
  _globals['_ADDREQUEST']._serialized_end=54
  _globals['_ADDREPLY']._serialized_start=56
  _globals['_ADDREPLY']._serialized_end=79
  _globals['_IMAGEREQUEST']._serialized_start=81
  _globals['_IMAGEREQUEST']._serialized_end=110
  _globals['_JSONIMAGEREQUEST']._serialized_start=112
  _globals['_JSONIMAGEREQUEST']._serialized_end=149
  _globals['_IMAGEREPLY']._serialized_start=151
  _globals['_IMAGEREPLY']._serialized_end=194
  _globals['_DOTREQUEST']._serialized_start=196
  _globals['_DOTREQUEST']._serialized_end=230
  _globals['_DOTREPLY']._serialized_start=232
  _globals['_DOTREPLY']._serialized_end=255
  _globals['_LAB6']._serialized_start=258
  _globals['_LAB6']._serialized_end=458
# @@protoc_insertion_point(module_scope)
